# Generated by Django 5.1.11 on 2025-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
