# Generated by Django 5.1.11 on 2025-06-12 14:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(upload_to=accounts.models.staff_photo_upload_path, verbose_name='Hodim surati'),
        ),
    ]
