# Generated by Django 5.1.11 on 2025-06-12 14:06

import django.db.models.deletion
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', student.models.AutoIncrementField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_in_dormitory', models.BooleanField(default=True)),
                ('parent_full_name', models.CharField(max_length=100)),
                ('parent_login', models.CharField(editable=False, max_length=150, unique=True)),
                ('parent_password', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=student.models.student_image_upload_to)),
                ('contract_number', models.CharField(max_length=50)),
                ('contract_date', models.DateField()),
                ('arrival_time', models.DateField()),
                ('checkout_time', models.DateField(blank=True, null=True)),
                ('total_payment', models.PositiveIntegerField()),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='dormitory.dormitory')),
            ],
        ),
    ]
