# Generated by Django 5.1.11 on 2025-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_payment',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
