# Generated by Django 5.1.11 on 2025-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
