# Generated by Django 5.1.11 on 2025-08-22 19:24

import student.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=student.models.AutoIncrementField(primary_key=True, serialize=False),
        ),
    ]
