# Generated by Django 5.1.11 on 2025-09-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_login',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
