# Generated by Django 5.1.11 on 2025-10-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='total_payment',
        ),
    ]
