# Generated by Django 5.1.11 on 2025-10-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_login',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
