# Generated by Django 5.1.11 on 2025-06-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ipaddress',
            field=models.CharField(max_length=25),
        ),
    ]
