# Generated by Django 5.1.11 on 2025-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_alter_device_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='monthly_payment',
            field=models.PositiveIntegerField(default=0, verbose_name="Oylik to‘lov miqdori (so'm)"),
        ),
    ]
