# Generated by Django 5.1.11 on 2025-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_dormitory_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='default_monthly_payment',
            field=models.PositiveIntegerField(default=1, help_text='Shartnomaga asosan boshlang‘ich oylik to‘lov (so‘mda)'),
        ),
    ]
