# Generated by Django 5.1.11 on 2025-06-25 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dormitory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.dormitory'),
            preserve_default=False,
        ),
    ]
