# Generated by Django 5.1.11 on 2025-07-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0006_room_dormitory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
