# Generated by Django 5.1.11 on 2025-09-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0007_dormitory_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
