# Generated by Django 5.1.11 on 2025-10-23 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0007_dormitory_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dormitory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='dormitory.dormitory'),
        ),
    ]
