# Generated by Django 5.1.11 on 2025-10-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0008_alter_room_dormitory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('dormitory', 'number'), name='unique_room_per_dormitory'),
        ),
    ]
