# Generated by Django 5.1.11 on 2025-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0008_alter_room_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Xona', 'verbose_name_plural': 'Xonalar'},
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('dormitory', 'number')},
        ),
    ]
