# Generated by Django 5.1.11 on 2025-10-27 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0009_room_unique_room_per_dormitory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dormitory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.dormitory'),
        ),
    ]
