# Generated by Django 5.1.11 on 2026-01-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0010_alter_room_dormitory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='To‘lov bo‘lishi kerak bo‘lgan oxirgi sana'),
        ),
    ]
